### ISSUE TITLE
当接口需要添加Header时默认使用ApacheHttpClient存在错误

### ISSUE THREAD

**Issue by chi-cat** [firelcw/easy-http#2]
https://github.com/vizaizai/easy-http/blob/fe31ed2bdefbe102766b3c4fa94feffc76bcf198/src/main/java/com/github/vizaizai/client/ApacheHttpClient.java#L88

https://github.com/vizaizai/easy-http/blob/fe31ed2bdefbe102766b3c4fa94feffc76bcf198/src/main/java/com/github/vizaizai/client/ApacheHttpClient.java#L135

请检查此处的header添加逻辑

**Comment by vizaizai** [comment]
感谢你的指出，问题已修复
